export const DEFAULT_SUPPLEMENTS = [
  {
    name: 'Wegovy oral 1.5mg',
    brand: 'Novo Nordisk',
    category: 'Prescription',
    dose_per_serving: '1 tablet',
    servings_per_day: 1,
    timing: ['wake'],
    timing_notes: 'On waking, empty stomach. No food, water, or supplements for 30 min after.',
    nutrients: [],
    active: true,
  },
  {
    name: 'Thorne Iron Bisglycinate',
    brand: 'Thorne',
    category: 'Minerals',
    dose_per_serving: '1 cap',
    servings_per_day: 1,
    timing: ['wake_30'],
    timing_notes: 'Empty stomach, 30 min after waking. Take with Vitamin C 500mg.',
    nutrients: [
      { name: 'Iron', amount: 25, unit: 'mg', dv_percent: 139 },
    ],
    active: true,
  },
  {
    name: 'Nature Made Fish Oil 1200mg',
    brand: 'Nature Made',
    category: 'Omega Fatty Acids',
    dose_per_serving: '2 softgels',
    servings_per_day: 1,
    timing: ['first_meal'],
    timing_notes: 'With first meal.',
    nutrients: [
      { name: 'Omega-3 Fatty Acids', amount: 720, unit: 'mg', dv_percent: null },
      { name: 'DHA', amount: 600, unit: 'mg', dv_percent: null },
    ],
    active: true,
  },
  {
    name: 'Nature Made Multi For Him No Iron',
    brand: 'Nature Made',
    category: 'Multivitamin',
    dose_per_serving: '1 tablet',
    servings_per_day: 1,
    timing: ['first_meal'],
    timing_notes: 'With first meal.',
    nutrients: [
      { name: 'Vitamin A', amount: 900, unit: 'mcg', dv_percent: 100 },
      { name: 'Vitamin C', amount: 90, unit: 'mg', dv_percent: 100 },
      { name: 'Vitamin D3', amount: 25, unit: 'mcg', dv_percent: 125 },
      { name: 'Vitamin E', amount: 15, unit: 'mg', dv_percent: 100 },
      { name: 'Vitamin K', amount: 80, unit: 'mcg', dv_percent: 67 },
      { name: 'Thiamin (B1)', amount: 1.2, unit: 'mg', dv_percent: 100 },
      { name: 'Riboflavin (B2)', amount: 1.3, unit: 'mg', dv_percent: 100 },
      { name: 'Niacin (B3)', amount: 16, unit: 'mg', dv_percent: 100 },
      { name: 'Vitamin B6', amount: 1.7, unit: 'mg', dv_percent: 100 },
      { name: 'Folate', amount: 400, unit: 'mcg DFE', dv_percent: 100 },
      { name: 'Vitamin B12', amount: 18, unit: 'mcg', dv_percent: 750 },
      { name: 'Biotin', amount: 30, unit: 'mcg', dv_percent: 100 },
      { name: 'Pantothenic Acid', amount: 5, unit: 'mg', dv_percent: 100 },
      { name: 'Calcium', amount: 162, unit: 'mg', dv_percent: 12 },
      { name: 'Iodine', amount: 150, unit: 'mcg', dv_percent: 100 },
      { name: 'Zinc', amount: 11, unit: 'mg', dv_percent: 100 },
      { name: 'Selenium', amount: 55, unit: 'mcg', dv_percent: 100 },
      { name: 'Copper', amount: 0.9, unit: 'mg', dv_percent: 100 },
      { name: 'Manganese', amount: 2.3, unit: 'mg', dv_percent: 100 },
      { name: 'Chromium', amount: 35, unit: 'mcg', dv_percent: 100 },
      { name: 'Molybdenum', amount: 45, unit: 'mcg', dv_percent: 100 },
    ],
    active: true,
  },
  {
    name: 'NOW Foods Probiotic-10 25 Billion',
    brand: 'NOW Foods',
    category: 'Probiotics',
    dose_per_serving: '1–2 caps',
    servings_per_day: 2,
    timing: ['between_meals'],
    timing_notes: 'Between meals (mid-afternoon).',
    nutrients: [
      { name: 'Probiotic Cultures', amount: 25, unit: 'billion CFU', dv_percent: null },
    ],
    active: true,
  },
  {
    name: 'Nature Made Magnesium Glycinate 200mg',
    brand: 'Nature Made',
    category: 'Minerals',
    dose_per_serving: '2 caps',
    servings_per_day: 1,
    timing: ['evening'],
    timing_notes: 'Evening with dinner.',
    nutrients: [
      { name: 'Magnesium', amount: 200, unit: 'mg', dv_percent: 48 },
    ],
    active: true,
  },
  {
    name: 'Bloom Greens & Superfoods (Orange Passionfruit)',
    brand: 'Bloom Nutrition',
    category: 'Other',
    dose_per_serving: '1 scoop (6.12g)',
    servings_per_day: 1,
    timing: ['first_meal'],
    timing_notes: 'Mix with 8–12 oz cold water or smoothie. Drink immediately.',
    suggested_use: 'Add 1 scoop to 8-12 fluid ounces of cold water, juice, or smoothie and mix well. Drink immediately after mixing. 1 to 2 servings daily.',
    cautions: 'Before taking any new supplement, consult your health care provider if you have medical conditions, take prescription medications or are pregnant or lactating. Store in a cool, dry place. Keep out of reach of children. Dairy free, Non-GMO.',
    other_ingredients: ['Natural Flavors', 'Citric Acid', 'Stevia Leaf Extract'],
    nutrients: [
      { name: 'Calories',           amount: 20,  unit: 'kcal', dv_percent: null },
      { name: 'Total Carbohydrate', amount: 4,   unit: 'g',    dv_percent: 1 },
      { name: 'Dietary Fiber',      amount: 2,   unit: 'g',    dv_percent: 7 },
      { name: 'Total Sugars',       amount: 1,   unit: 'g',    dv_percent: null },
      { name: 'Sodium',             amount: 8,   unit: 'mg',   dv_percent: null },
      { name: 'Vitamin B12',        amount: 3.6, unit: 'mcg',  dv_percent: 150 },
      { name: 'Iron',               amount: 0.5, unit: 'mg',   dv_percent: 3 },
    ],
    active: true,
  },
  {
    name: 'Grass Fed Collagen Peptides',
    brand: 'Garden of Life',
    category: 'Amino Acids',
    dose_per_serving: '1 scoop (20g)',
    servings_per_day: 1,
    timing: ['first_meal'],
    timing_notes: 'Type I and III collagen, unflavored.',
    nutrients: [
      { name: 'Protein', amount: 18, unit: 'g', dv_percent: null },
      { name: 'Collagen Peptides', amount: 20, unit: 'g', dv_percent: null },
    ],
    active: true,
  },
  {
    name: 'Double Strength L-Theanine 200mg',
    brand: "Nature's Truth",
    category: 'Amino Acids',
    dose_per_serving: '1 capsule',
    servings_per_day: 1,
    timing: ['bedtime'],
    timing_notes: 'Take on empty stomach, 1 hour before bed.',
    nutrients: [
      { name: 'L-Theanine', amount: 200, unit: 'mg', dv_percent: null },
    ],
    active: true,
  },
  {
    name: 'D3 + K2',
    brand: 'Nature Made',
    category: 'Vitamins',
    dose_per_serving: '1 softgel',
    servings_per_day: 1,
    timing: ['first_meal'],
    timing_notes: 'Fat soluble, take with food.',
    nutrients: [
      { name: 'Vitamin D3', amount: 125, unit: 'mcg', dv_percent: 625 },
      { name: 'Vitamin K2', amount: 100, unit: 'mcg', dv_percent: null },
    ],
    active: true,
  },
  {
    name: 'Trazodone',
    brand: '',
    category: 'Prescription',
    dose_per_serving: '1 tablet',
    servings_per_day: 1,
    timing: ['bedtime'],
    timing_notes: 'Take 1 hour before sleep with Magnesium Glycinate and L-Theanine.',
    nutrients: [],
    active: true,
  },
]

export const TIMING_LABELS = {
  wake: 'On Waking',
  wake_30: 'Wake + 30min',
  first_meal: 'First Meal',
  between_meals: 'Between Meals',
  evening: 'Evening',
  bedtime: 'Bedtime',
}

export const CATEGORY_COLORS = {
  'Vitamins': '#4f86c6',
  'Minerals': '#1a6b4a',
  'Omega Fatty Acids': '#f59e0b',
  'Probiotics': '#8b5cf6',
  'Multivitamin': '#ec4899',
  'Prescription': '#ef4444',
  'Herbal': '#10b981',
  'Amino Acids': '#06b6d4',
  'Other': '#94a3b8',
}

export const KEY_NUTRIENTS = [
  'Vitamin D3', 'Iron', 'Vitamin B12', 'Magnesium', 'Zinc',
  'Vitamin C', 'Vitamin A', 'Vitamin K', 'Calcium', 'Potassium',
  'Folate', 'Vitamin B6', 'Iodine', 'Selenium', 'Vitamin E',
]
